version: "3.3"

services:
  web:
    image: ghcr.io/annaberezko/test_docker/backend:celery
    build: ./
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/usr/src/app/
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - django_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    image: ghcr.io/annaberezko/test_docker/backend:celery
    command: celery -A test_docker worker -l info
    restart: unless-stopped
    depends_on:
      - redis

  celerybeat:
    image: ghcr.io/annaberezko/test_docker/backend:celery
    command: celery -A test_docker beat -l info
    restart: unless-stopped
    depends_on:
      - redis
      - celery

# save data
volumes:
  django_postgres_data:
