version: "3.3"

services:
  web:
    build: ./
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/usr/src/app/
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - django_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

# save data
volumes:
  django_postgres_data: