name: Deploy
on:
  push:
    branches: [ master ]
jobs:
#  tests:
#    uses: ./.github/workflows/tests.yml


# github container registry
  build-backend:
#    needs: [ tests ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.3.0
        with:
          registry: ghcr.io
          username: annaberezko
          password: ${{ secrets.CR_PAT }}

      - name: build and push

        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          install: true
          tags: ghcr.io/annaberezko/test_docker/back:latest
          file: Dockerfile
          cache-from: type=registry,ref=ghcr.io/annaberezko/test_docker/back:buildcache
          cache-to: type=registry,ref=ghcr.io/annaberezko/test_docker/back:buildcache,mode=max

#  deploy:
##    needs: [build-backend]
#    runs-on: ubuntu-latest
#    env:
#      HOST: ${{ secrets.DEV_HOST }}
#
#    steps:
##      - name: Change HOST if main
##        if: github.ref == 'refs/heads/main'
##        run: echo "HOST=${{ secrets.PROD_HOST }}" >> $GITHUB_ENV
#
#      - name: deploy command
#        uses: appleboy/ssh-action@master
#        with:
#          # ec2-3-239-231-173.compute-1.amazonaws.com
#          host: ${{ secrets.DEV_HOST }}
#          # ubuntu
#          username: ${{ secrets.DEV_USERNAME }}
#          key: ${{ secrets.DEV_KEY }}
#          script: |
#            sudo ls -la
##            sudo docker pull ghcr.io/${{ github.actor }}/test_docker:${{ github.head_ref || github.ref_name }}
##            sudo docker-compose down
##            sudo docker-compose up -d
##            sudo docker system prune -a -f
