name: Deploy
on:
  push:
    branches: [ master ]

jobs:
#  tests:
#    uses: ./.github/workflows/tests.yml

  build-backend:
#    needs: [ tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
#          secrets: |
#            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
          tags: ghcr.io/${{ github.actor }}/backend:${{ github.head_ref || github.ref_name }}
#          file: Dockerfile
#          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/backend:buildcache
#          cache-to: type=registry,ref=ghcr.io/${{ github.actor }}/backend:buildcache,mode=max

  deploy:
#    needs: [build-backend]
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.DEV_HOST }}

    steps:
#      - name: Change HOST if main
#        if: github.ref == 'refs/heads/main'
#        run: echo "HOST=${{ secrets.PROD_HOST }}" >> $GITHUB_ENV

      - name: deploy command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          script: |
            sudo ls -la
#            sudo docker pull ghcr.io/rion-energie/platform/backend:${{ github.head_ref || github.ref_name }}
#            cd platform
#            sudo docker-compose down
#            sudo docker-compose up -d
#            sudo docker system prune -a -f
